apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-aicp-perf
  labels:
    app: aicp-perf-tool
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: api
      port: {{ .Values.service.proxyPort }}
      targetPort: api
    - name: ssh
      port: {{ .Values.service.sshPort }}
      targetPort: ssh
  selector:
    app: aicp-perf-tool
